### ISSUE TITLE
is blocking CDN requests

### ISSUE THREAD

**Issue by Gaarmy** [yandeu/five-server-vscode#10]
Recently in my projects the console marks these problems that are the requests of CDNs

Before I did not have the CORS activated, nor the middleware, but now it does not work in any way

![Screenshot 2021-11-24 160513](https://user-images.githubusercontent.com/33444101/143319036-e2a9f033-4367-45ab-a448-25aeed145c3d.jpg)
 
Anyway thanks for the plugin it's very good

**Comment by yandeu** [comment]
> Anyway thanks for the plugin it's very good

Thanks!

Try:

```js
const customHeaders = (req, res, next) => {
  res.setHeader('Cross-Origin-Embedder-Policy', 'unsafe-none')
  res.setHeader('Cross-Origin-Opener-Policy', 'unsafe-none')
  res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin')
  next()
}
```

**Comment by yandeu** [comment]
I just uploaded a new version of five-server (v0.1.1), please test if it work without any customHeaders.

**Comment by Gaarmy** [comment]
> I just uploaded a new version of five-server (v0.1.1), please test if it work without any customHeaders.

Yeah, is working

Thanks!
