### ISSUE TITLE
Last saved file is automatically opened in the browser

### ISSUE THREAD

**Issue by AlexIII** [yandeu/five-server-vscode#11]
Hi!
After updating to 0.1.0 last saved file is automatically opened in the browser.
This needs to be disabled by default. I don't need browser to open *.css or *.ts file I've just edited.
Reverting to 0.0.34 as it does not have this behavior.

**Comment by yandeu** [comment]
Thanks for reporting.

I have already fix it in https://github.com/yandeu/five-server-vscode/commit/03d9c0c55b3c4480995791f92114c3c054978d30.

Should be fixe once I release the next version.

**Comment by yandeu** [comment]
I have publish v0.1.2.

Please wait few minutes till it is available and test it.

**Comment by AlexIII** [comment]
v0.1.2 fixes that problem. Thank you.
