### ISSUE TITLE
Compatibility of "hightlight"-feature with tailwindcss

### ISSUE THREAD

**Issue by Cayllen** [yandeu/five-server-vscode#15]
**Describe the bug**
It seems the highlight feature is not compatible with tailwindcss. When trying to highlight elements, only some are highlighted, but mostly only the outer elements are highlighted:

What I did:
- I selected the href with my cursor in vscode
- But in my browser, the whole div is highlighted
![image](https://user-images.githubusercontent.com/27898791/161404593-5ebfe165-44c8-4caa-bb7c-5ab2d3704136.png)

If necessary I can also upload the code

**Comment by yandeu** [comment]
Maybe because `- Template by` is not inside a tag?
What if you wrap the 2 `<a>` and the text inside a paragraph?

**Comment by Cayllen** [comment]
Fixed it! Thanks! Is there any way to change the style how text is highlighted? Right now it is a bit too much covering up what I'm actually working on

**Comment by yandeu** [comment]
I guess I could add a `highlightOpacity` option.

**Comment by Cayllen** [comment]
Would definitely be an useful option!
