### ISSUE TITLE
Failed to Tokenize error, is there a way to solve?

### ISSUE THREAD

**Issue by PsyPeke** [yandeu/five-server-vscode#18]
I used to work with HTML that is integrated with another markup language (a kind of xml custom that is not recognize by VSCode), and I've notice that Live server doesn't show highlight.
With debug on, I've found out that maybe the problem is this failed to tokenize error on a specific unrecognized tag?
I can see highlight in correct html file, but not if there is some unrecognized tag, it this normal? Is there any workaround?

**Comment by yandeu** [comment]
Is this similar to https://github.com/yandeu/five-server-vscode/issues/17?
