### ISSUE TITLE
request get error

### ISSUE THREAD

**Issue by lavaicer** [yandeu/five-server-vscode#26]
**Describe the bug**
when I access my site page through GET/POST method,I got I 500 ERROR. php-8.1

```php
isset($_GET['r'])?$register_tag = $_GET['r']:$register_tag = NULL;
echo "well";
echo $register_tag;
```

**Have a question?**
Join the [discussions](https://github.com/yandeu/five-server/discussions) instead.

**Comment by yandeu** [comment]
See https://github.com/yandeu/five-server-vscode#about-php

**Comment by lavaicer** [comment]
> See [yandeu/five-server-vscode#about-php](https://github.com/yandeu/five-server-vscode#about-php)

thx!

**Comment by yandeu** [comment]
You're welcome :)
