### ISSUE TITLE
[BUG] Five Server showing Tabnine

### ISSUE THREAD

**Issue by VincentTam** [yandeu/five-server-vscode#27]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5748535/191488368-814ebe91-746c-49a5-8787-45f0765aced0.png)
![image](https://user-images.githubusercontent.com/5748535/191488456-f7b95f8e-452f-4c92-a00f-ec9fcf585cc4.png)

I opened the server, and I saw the Tabnine Tab.

**Have a question?**
Join the [discussions](https://github.com/yandeu/five-server/discussions) instead.

**Comment by yandeu** [comment]
Maybe you still have an old service worker installed?

Try to clear all data for 127.0.0.1:5555 and localhost:5555

**Comment by VincentTam** [comment]
Thank you for reply.  My bad.  The default `5555` is used by Tabnine.  I changed the port number and it worked.
