### ISSUE TITLE
Server doesn't respect "fiveServer.port" config

### ISSUE THREAD

**Issue by Supportic** [yandeu/five-server-vscode#3]
**Describe the bug**
I tried to open my workspace or just the folder. Neither it takes my workspace settings nor the ./vscode/settings.json under consideration when starting the server.

e.g. **workspace.code-workspace**
```json
{
  "folders": [
    {
      "path": ".",
      "name": "Example"
    }
  ],
  "settings": {
    "fiveServer.port": 8000,
  }
}
```

**Comment by yandeu** [comment]
I guess I have to fix this. 

For now, please use a `.fiveserverrc.json` or `fiveserver.config.js` file:

```json
// .fiveserverrc.json
{
    "port": 8000
}
```

```js
// fiveserver.config.js
module.exports = {
    port: 8000
}
```

**Comment by yandeu** [comment]
Fix! Should work once the next version is released.
