### ISSUE TITLE
ERROR: Error: listen EACCES: permission denied 0.0.0.0

### ISSUE THREAD

**Issue by shagariboy** [yandeu/five-server-vscode#43]
**Describe the bug**
Version: 1.79.2 (user setup)
Commit: https://github.com/microsoft/vscode/commit/695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
VS Code version: Code 1.79.2 (https://github.com/microsoft/vscode/commit/695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621

Step 1: open vscode
Step 2: click :"go live"
Step 3: error on terminal : ERROR: Error: listen EACCES: permission denied 0.0.0.0

each time I click "go live", I get this error on the terminal:ERROR: Error: listen EACCES: permission denied 0.0.0.0

<img width="960" alt="Screenshot 2023-07-01 085922" src="https://github.com/yandeu/five-server-vscode/assets/45914831/0be3f07b-893b-436b-b8ab-82ae94d89c74">
<img width="960" alt="Screenshot 2023-07-01 231901" src="https://github.com/yandeu/five-server-vscode/assets/45914831/0bde2fa4-cbaa-4f56-a27d-fa4277175ee7">

**Have a question?**
Join the [discussions](https://github.com/yandeu/five-server/discussions) instead.

**Comment by yandeu** [comment]
Looks like you can't run the server on `0.0.0.0`, which is the default. Find the `host` setting for five-server and set it to `localhost`.

Or try to adjust your Windows firewall setting.

**Comment by shagariboy** [comment]
changing to localhost worked. Thank you very much

**Comment by yandeu** [comment]
You're welcome :)
