### ISSUE TITLE
Activate Extension on Specific Files or Languages

### ISSUE THREAD

**Issue by YaduAhuja** [yandeu/five-server-vscode#5]
Can't we change `*` to `onlanguage` activation-events to support the languages that can be run with five-server and ignore every other language so that VSCode's startup speed is Increased?

Currently, Five-Server on my System is using near about 1 sec to run even when I am running CPP or Java files and it will be great if this feature is added.

Below is the Screenshot of Runtime:

![Running](https://user-images.githubusercontent.com/66440500/126145362-12494ba3-36e3-4322-895a-b362d699f1e6.jpeg)

**Comment by yandeu** [comment]
What about just lazy loading `five-server`? It reduced the startup time for me to only 10 -  50ms.

```diff
# /src/extension.ts

  if (!fiveServer) {
-   fiveServer = new FiveServer();
+   const FiveServer = await import("five-server");
+   fiveServer = new FiveServer.default();
    startWorkers = true;
}
````

**Comment by yandeu** [comment]
See https://github.com/yandeu/five-server-vscode/commit/51c184b008e7d6886c63ec1a66e38615651c7b61

**Comment by YaduAhuja** [comment]
Thank You!! now the startup time has been reduced to 13ms. Also when will this update reflect in vscode marketplace or  I download and compile extension myself?


![Screenshot (5)](https://user-images.githubusercontent.com/66440500/126991602-1077caae-29dd-44ce-99f1-2562256cb0ff.png)

**Comment by yandeu** [comment]
Nice!!

I don't know when the next version will be released. 

Yes, probably you should compile it yourself (using the same release version) and wait for the official update 👍
