### ISSUE TITLE
Adjust the menu order or make the menu configurable

### ISSUE THREAD

**Issue by gwsbhqt** [yandeu/five-server-vscode#7]
I think the order of the right-click menu should not be set to the top, whether it would be better to adjust to the arrow, or provide configuration items to adjust.

Every time I want to create a new file, I click the wrong menu, which is very frustrating.

But no matter what, thank you for your effort.

![image](https://user-images.githubusercontent.com/16471930/133403525-435e9e74-868f-490a-bc9c-1e63a6e01905.png)

**Comment by yandeu** [comment]
> But no matter what, thank you for your effort.

You're welcome :)

> I think the order of the right-click menu should not be set to the top, whether it would be better to adjust to the arrow, or provide configuration items to adjust.

You're right. I will move it.
