### ISSUE TITLE
injectBody removes body classes

### ISSUE THREAD

**Issue by viveksjain** [yandeu/five-server-vscode#8]
Hot reload with injectBody looks awesome, however, it seems to clear the `class` attribute on body which messes up some of the formatting on my HTML.

**Comment by yandeu** [comment]
It's probably just https://github.com/yandeu/five-server/blob/2fb91e2a55a72c67e49b5f9f3f0ad7fc022a8da5/client/injected.ts#L199.

I will check it soon 👍🏻

**Comment by viveksjain** [comment]
Thanks so much for the quick fix! I took a quick look at the code, looks like you already have the object `newBody`, can that be used directly for diff? Fixing id and class is good enough for me but technically it still doesn't handle some attributes.

**Comment by yandeu** [comment]
I can't remember why I used `tmp` instead of `newBody` for diffing.

I believe `domParser` is just there to throw an error if `d` is invalid.
